// <auto-generated />
using System;
using AlienCyborgESPRadar;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlienCyborgESPRadar.Migrations.BatteryDb
{
    [DbContext(typeof(BatteryDbContext))]
    [Migration("20260126013632_BatteryDbInit")]
    partial class BatteryDbInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlienCyborgESPRadar.BatteryLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool?>("BatteryOk")
                        .HasColumnType("bit");

                    b.Property<double?>("BatteryPercent")
                        .HasColumnType("float");

                    b.Property<double?>("BatteryVoltage")
                        .HasColumnType("float");

                    b.Property<byte?>("Max17048ChipId")
                        .HasColumnType("tinyint");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BatteryLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
