// <auto-generated />
using System;
using AlienCyborgESPRadar;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlienCyborgESPRadar.Migrations.BatteryDb
{
    [DbContext(typeof(BatteryDbContext))]
    [Migration("20260126021207_BatteryDbInitPk2")]
    partial class BatteryDbInitPk2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlienCyborgESPRadar.BatteryLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool?>("BatteryOk")
                        .HasColumnType("bit");

                    b.Property<double?>("BatteryPercent")
                        .HasColumnType("float");

                    b.Property<double?>("BatteryVoltage")
                        .HasColumnType("float");

                    b.Property<byte?>("Max17048ChipId")
                        .HasColumnType("tinyint");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RadarLogId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RadarLogId")
                        .IsUnique()
                        .HasFilter("[RadarLogId] IS NOT NULL");

                    b.ToTable("BatteryLogs");
                });

            modelBuilder.Entity("AlienCyborgESPRadar.GpsLogs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("FixAgeMs")
                        .HasColumnType("int");

                    b.Property<bool?>("GpsFix")
                        .HasColumnType("bit");

                    b.Property<bool?>("GpsPresent")
                        .HasColumnType("bit");

                    b.Property<int?>("HdopX100")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RadarLogId")
                        .HasColumnType("bigint");

                    b.Property<string>("RawJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Satellites")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("RadarLogId")
                        .IsUnique()
                        .HasFilter("[RadarLogId] IS NOT NULL");

                    b.ToTable("GpsLogs");
                });

            modelBuilder.Entity("AlienCyborgESPRadar.RadarLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Motion")
                        .HasColumnType("bit");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("TsMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("RadarLog");
                });

            modelBuilder.Entity("AlienCyborgESPRadar.BatteryLog", b =>
                {
                    b.HasOne("AlienCyborgESPRadar.RadarLog", "RadarLog")
                        .WithOne("BatteryLog")
                        .HasForeignKey("AlienCyborgESPRadar.BatteryLog", "RadarLogId");

                    b.Navigation("RadarLog");
                });

            modelBuilder.Entity("AlienCyborgESPRadar.GpsLogs", b =>
                {
                    b.HasOne("AlienCyborgESPRadar.RadarLog", "RadarLog")
                        .WithOne("GpsLog")
                        .HasForeignKey("AlienCyborgESPRadar.GpsLogs", "RadarLogId");

                    b.Navigation("RadarLog");
                });

            modelBuilder.Entity("AlienCyborgESPRadar.RadarLog", b =>
                {
                    b.Navigation("BatteryLog");

                    b.Navigation("GpsLog");
                });
#pragma warning restore 612, 618
        }
    }
}
